In [1]:
import numpy as np

In [2]:
marks = np.array([[85,90,88],[78,82,80],[92,95,94]])

In [3]:
marks

array([[85, 90, 88],
       [78, 82, 80],
       [92, 95, 94]])

In [4]:
np.mean(marks,axis=1)

array([87.66666667, 80.        , 93.66666667])

In [5]:
marks.max()

np.int64(95)

In [6]:
np.mean(marks,axis=0)

array([85.        , 89.        , 87.33333333])

In [7]:
np.argmax(np.mean(marks,axis=1))

np.int64(2)

In [8]:
np.sum(marks,axis=1)

array([263, 240, 281])

In [9]:
np.max(marks,axis=0)

array([92, 95, 94])